import type { Metadata } from 'next'
import Link from 'next/link'
import { DOCS_PAGES, docsUrl } from '@/lib/docs'

const PAGE = DOCS_PAGES.find((p) => p.slug === 'privacy')!
const UPDATED = 'September 3, 2026'

// See the note in app/docs/terms/page.tsx — these are the counsel-owned values.
const LEGAL_ENTITY = 'Yeetful, Inc.'
const CONTACT = 'privacy@yeetful.com'

export const metadata: Metadata = {
  title: PAGE.seoTitle,
  description: PAGE.description,
  alternates: { canonical: docsUrl(PAGE.slug) },
  openGraph: { title: PAGE.seoTitle, description: PAGE.description, url: docsUrl(PAGE.slug), type: 'article' },
}

export default function PrivacyPage() {
  return (
    <>
      <p className="docs__crumbs mono">
        <Link href="/docs">DOCS</Link> <span>/</span> PRIVACY POLICY
      </p>
      <h1 className="docs__h1">Privacy Policy</h1>
      <p className="docs__lead">
        Pantessa is non-custodial and collects as little as it can to run the Service. This policy
        explains what we collect, why, who we share it with, and what stays public on-chain.
      </p>

      <div className="docs__prose">
        <p>
          <strong>Last updated:</strong> {UPDATED}
        </p>
        <p>
          This Privacy Policy describes how <strong>{LEGAL_ENTITY}</strong>, doing business as
          Pantessa (&ldquo;Pantessa,&rdquo; &ldquo;we&rdquo;), handles information when you use the
          Pantessa website, chat interface, dashboard, embeddable widget, SDK, and APIs (the
          &ldquo;Service&rdquo;). By using the Service you agree to this policy. It works alongside
          our <Link href="/docs/terms">Terms of Service</Link>.
        </p>

        <h2>1. Information we collect</h2>
        <p>
          <strong>Wallet and on-chain data.</strong> Your public wallet address, the Sign-In With
          Ethereum signatures you produce, consent signatures you provide for specific actions, and
          the on-chain records (amounts, assets, counterparties, transaction hashes) generated by
          transactions you sign. Blockchain data is public and permanent by design.
        </p>
        <p>
          <strong>Sign-in and account data.</strong>{' '}When you sign in or create an embedded wallet,
          authentication is handled by Coinbase Developer Platform (&ldquo;CDP&rdquo;). Depending on
          the method, we or CDP receive: your <strong>email address</strong> (email sign-in), or
          basic profile details from <strong>Google or X</strong>{' '}single sign-on (such as your name,
          email, and a provider account identifier). We never receive your Google, X, or wallet
          password, and the embedded wallet&rsquo;s private keys are held in CDP&rsquo;s secure
          infrastructure, not by us.
        </p>
        <p>
          <strong>What you type.</strong> The requests you write in the chat interface, the
          conversation history attached to your account, and any handle, branding, or link content
          you publish. When a request that involved money could not be completed, we log the text of
          that request together with a summary of the balances that were available, so we can find
          and fix the gap.
        </p>
        <p>
          <strong>Usage and ledger data.</strong> API key metadata (we store only a hash of each
          secret, never the secret itself), spend grants and approvals, organizations and members,
          jobs and scheduled actions you create, receipts for settled and refused calls, and
          telemetry about transactions prepared, signed, or abandoned, including on sites that embed
          our widget.
        </p>
        <p>
          <strong>Technical data.</strong> Server and request logs, your{' '}
          <strong>IP address</strong>, and a secure httpOnly session cookie for signed-in sessions.
          We use your IP address to apply rate limits and prevent abuse, and we store it in hashed
          form for that purpose. Where a fiat on-ramp provider requires it to determine whether it
          can serve you, your IP address may be sent to that provider. We also keep aggregate,
          privacy-preserving analytics about site usage.
        </p>
        <p>
          <strong>Payment data.</strong> If you subscribe to a paid plan, payment is processed by
          Stripe. We receive subscription status and billing metadata; we do not receive or store
          your full card details. If you buy crypto through a fiat on-ramp, that purchase is handled
          by the on-ramp provider under its own policy, and we do not receive your payment details.
        </p>

        <h2>2. Single sign-on (Google, X) and email</h2>
        <p>
          Social sign-in (&ldquo;SSO&rdquo;) and email sign-in are provided through Coinbase CDP&rsquo;s
          embedded-wallet authentication. When you choose &ldquo;Continue with Google&rdquo; or
          &ldquo;Continue with X,&rdquo; you authenticate with that provider, which returns a limited
          set of profile information (typically email, name, and an account identifier) used to
          create or sign you into your Pantessa embedded wallet. We use this only to authenticate you,
          create your account, and contact you about the Service. We do not post to your social
          accounts or access your contacts. Your use of Google or X is also governed by their own
          privacy policies, and your use of the embedded wallet by Coinbase&rsquo;s privacy policy.
          You can use a self-custodied wallet instead if you prefer not to use SSO or email.
        </p>

        <h2>3. AI processing of your requests</h2>
        <p>
          The Service uses a third-party AI model provider to interpret what you ask for. The text
          of your request, and context such as which integrations you have enabled and the public
          balances we read for your wallet, may be sent to that provider so it can be understood and
          routed. We currently use Anthropic for this.
        </p>
        <p>
          The model interprets your request and helps choose a route. It does not write the
          transaction: transaction data is generated by our own code from a fixed set of builders
          and independently re-checked before it is shown to you. Please do not paste private keys,
          seed phrases, or other secrets into the chat.
        </p>

        <h2>4. How we use information</h2>
        <ul>
          <li>provide, operate, and secure the Service and your account;</li>
          <li>interpret your requests and prepare the transactions you ask for;</li>
          <li>enforce spend controls and produce receipts and ledgers;</li>
          <li>run jobs, schedules, and protective actions you have explicitly enabled;</li>
          <li>route calls to third-party services you select or that the engine selects;</li>
          <li>prevent fraud, abuse, and security incidents, and comply with law;</li>
          <li>
            diagnose failures — including reviewing requests that could not be completed — and
            improve the Service;
          </li>
          <li>understand usage in aggregate;</li>
          <li>send you transactional or service-related messages.</li>
        </ul>

        <h2>5. How information is shared</h2>
        <p>We share information only as needed to run the Service:</p>
        <ul>
          <li>
            <strong>Service providers and processors</strong> — including Coinbase CDP
            (authentication, embedded wallets, and fiat on-ramp), Stripe (subscription billing, and
            fiat on-ramp where used), Anthropic (AI processing of your requests), blockchain node
            and data providers, our database and hosting providers, email delivery, and analytics.
            They process data on our behalf or under their own terms as described here.
          </li>
          <li>
            <strong>Fiat on-ramp providers</strong> — when you choose to buy crypto, we pass the
            destination wallet address, the amount, the asset and network, and where required your
            IP address, so the provider can create the purchase. The provider collects your identity
            and payment information directly from you under its own policy; we do not receive it.
          </li>
          <li>
            <strong>Third-party services and venues</strong> — when your request or the routing
            engine calls a service, the request is transmitted to that service, which handles it
            under its own policies.
          </li>
          <li>
            <strong>Public blockchain</strong> — transactions are written to a public ledger and are
            visible to anyone and effectively permanent.
          </li>
          <li>
            <strong>Content you publish</strong> — links, handles, public pages, and shared
            conversations you create are visible to anyone who has the address.
          </li>
          <li>
            <strong>Legal and safety</strong> — when required by law or to protect rights, safety,
            and the integrity of the Service.
          </li>
          <li>
            <strong>Business transfers</strong> — in connection with a merger, acquisition, or sale
            of assets, subject to this policy.
          </li>
        </ul>
        <p>
          We do not sell your personal information, and we do not share it for cross-context
          behavioural advertising.
        </p>

        <h2>6. On-chain data is public and permanent</h2>
        <p>
          Wallet addresses and transactions on the networks we support are public and cannot be
          deleted or altered by us or anyone else. The public activity surface shows network
          payments in an anonymized, aggregate form (wallets truncated, refusals shown only in
          aggregate), but the underlying chain data remains public. Consider this before
          transacting.
        </p>

        <h2>7. Cookies and sessions</h2>
        <p>
          We use a strictly-necessary, httpOnly session cookie to keep you signed in after a
          Sign-In With Ethereum signature, and privacy-preserving analytics. We do not use
          third-party advertising cookies and we do not track you across other websites.
        </p>

        <h2>8. Data retention</h2>
        <p>
          We keep information for as long as your account is active or as needed to provide the
          Service, then for the period required to meet legal, security, and accounting obligations.
          Logs and rate-limiting records are kept for a short period and then deleted or aggregated.
          On-chain records cannot be deleted.
        </p>

        <h2>9. Your choices and rights</h2>
        <p>
          You can disconnect your wallet, revoke API keys, revoke any authorization you granted for
          automated actions, delete chats, revoke links you published, and request deletion of
          account data by contacting us. We will honor applicable requests, except where data must be
          retained by law or exists immutably on-chain.
        </p>

        <h2>10. If you are in the EEA or the UK</h2>
        <p>
          Where the GDPR or UK GDPR applies, {LEGAL_ENTITY} is the controller of the personal data
          described here. We rely on these legal bases:
        </p>
        <ul>
          <li>
            <strong>Performance of a contract</strong> — to provide the Service you asked for,
            including interpreting your requests and preparing transactions;
          </li>
          <li>
            <strong>Legitimate interests</strong> — to secure the Service, prevent fraud and abuse,
            diagnose failures, and improve the product, balanced against your rights;
          </li>
          <li>
            <strong>Legal obligation</strong> — to meet accounting, tax, and law-enforcement
            requirements;
          </li>
          <li>
            <strong>Consent</strong> — where we ask for it, which you can withdraw at any time.
          </li>
        </ul>
        <p>
          You have the right to access, correct, erase, restrict, or object to processing of your
          personal data, to data portability, and to withdraw consent. You also have the right to
          lodge a complaint with your local supervisory authority. Where we transfer personal data
          outside the EEA or the UK, we rely on appropriate safeguards such as Standard Contractual
          Clauses. To exercise any right, contact us at {CONTACT}.
        </p>

        <h2>11. If you are in California</h2>
        <p>
          California residents have the right to know what personal information we collect and how
          we use and disclose it, to request deletion or correction, and not to be discriminated
          against for exercising those rights. We do not sell personal information or share it for
          cross-context behavioural advertising. Requests can be made at {CONTACT}.
        </p>

        <h2>12. Security and breach notification</h2>
        <p>
          We use reasonable technical and organizational measures to protect information (for
          example, storing only hashes of API key secrets, hashing IP addresses used for rate
          limiting, and keeping sessions in httpOnly cookies). No method of transmission or storage
          is perfectly secure, and you are responsible for safeguarding your wallet and credentials.
          If we become aware of a breach affecting your personal data, we will notify you and any
          relevant supervisory authority as required by applicable law and without undue delay.
        </p>

        <h2>13. Children</h2>
        <p>
          The Service is not directed to, and may not be used by, anyone under 18. We do not
          knowingly collect information from children.
        </p>

        <h2>14. International users</h2>
        <p>
          We and our providers may process information in countries other than yours, which may have
          different data-protection laws. Where required, we rely on appropriate safeguards for such
          transfers.
        </p>

        <h2>15. Changes</h2>
        <p>
          We may update this policy; we will revise the date above and, for material changes, provide
          additional notice where appropriate.
        </p>

        <h2>16. Contact</h2>
        <p>
          Privacy questions or requests: <strong>{CONTACT}</strong>.
        </p>
      </div>

      <div className="docs__callout">
        <p>
          This page describes how the Service actually handles data, but it is not legal advice.
          Qualified counsel should review it and confirm the processor list and regional disclosures
          before you rely on it.
        </p>
      </div>
    </>
  )
}
