// Robinhood Chain's tokenized equities — a STATIC snapshot of the Uniswap
// official token list for chain 4663 (https://tokens.uniswap.org), taken
// 2026-09-10 (202 entries; cbBTC dropped — it is a coin and charts as BTC).
//
// Why a static copy exists next to the live list (lib/token-list.ts): the
// chart resolver (lib/charts.ts) is PURE and CLIENT-SAFE — it decides,
// synchronously, whether a row grows the chart button and whether the
// candles proxy may touch a symbol. The live list is server-warmed and
// async, so the browser can't consult it. The harness pins the live warmed
// list against this snapshot (every live stock must be here), so a new
// listing fails a gate instead of silently staying chartless.
//
// Regenerate (paste the output over the table below):
//   node -e "fetch('https://tokens.uniswap.org').then(r=>r.json()).then(j=>console.log(j.tokens.filter(t=>t.chainId===4663&&t.symbol!=='cbBTC').sort((a,b)=>a.symbol.localeCompare(b.symbol)).map(t=>'  ['+JSON.stringify(t.symbol)+', '+JSON.stringify(t.name)+'],').join('\n')))"

/** [ticker, company name] for every listed equity, A→Z. */
export const ROBINHOOD_TICKERS: ReadonlyArray<readonly [string, string]> = [
  ["AAOI", "Applied Optoelectronics"],
  ["AAPL", "Apple"],
  ["ABCL", "AbCellera Biologics Inc."],
  ["ADBE", "Adobe Inc."],
  ["AEHR", "Aehr Test Systems"],
  ["AEIS", "Advanced Energy Industries Inc."],
  ["ALAB", "Astera Labs Inc."],
  ["AMAT", "Applied Materials"],
  ["AMBA", "Ambarella Inc."],
  ["AMC", "AMC Entertainment Holdings Inc."],
  ["AMD", "AMD"],
  ["AMKR", "Amkor Technology Inc."],
  ["AMZN", "Amazon"],
  ["ANET", "Arista Networks"],
  ["APLD", "Applied Digital"],
  ["APP", "Applovin Corporation"],
  ["ARM", "Arm Holdings plc"],
  ["ASML", "ASML Holding NV"],
  ["ASTS", "AST SpaceMobile"],
  ["AUR", "Aurora Innovation Inc."],
  ["AVAV", "AeroVironment Inc."],
  ["AVGO", "Broadcom"],
  ["AXON", "Axon Enterprise Inc."],
  ["AXTI", "AXT Inc"],
  ["BA", "Boeing"],
  ["BABA", "Alibaba"],
  ["BB", "BlackBerry Limited"],
  ["BE", "Bloom Energy"],
  ["BND", "Vanguard Total Bond Market ETF"],
  ["BULL", "Webull Corporation"],
  ["CASHCAT", "Cash Cat"],
  ["CBRS", "Cerebras Systems"],
  ["CCL", "Carnival Corporation"],
  ["CEG", "Constellation Energy Corporation"],
  ["CELH", "Celsius"],
  ["CIEN", "Ciena Corporation"],
  ["CLOV", "Clover Health Investments Corp."],
  ["CLS", "Celestica Inc."],
  ["CLSK", "CleanSpark"],
  ["COHR", "Coherent Corp."],
  ["COIN", "Coinbase"],
  ["COST", "Costco"],
  ["CRCL", "Circle Internet Group"],
  ["CRDO", "Credo Technology Group Holding Ltd"],
  ["CRM", "Salesforce Inc."],
  ["CRWD", "CrowdStrike Holdings"],
  ["CRWV", "CoreWeave"],
  ["CSCO", "Cisco Systems Inc."],
  ["CTSH", "Cognizant Technology Solutions Class A"],
  ["CVNA", "Carvana Co."],
  ["DDOG", "Datadog"],
  ["DELL", "Dell"],
  ["DJT", "Trump Media & Technology Group Corp."],
  ["DOCN", "DigitalOcean Holdings Inc."],
  ["DRAM", "Roundhill Memory ETF"],
  ["ELF", "e.l.f. Beauty"],
  ["EWT", "iShares MSCI Taiwan ETF"],
  ["EWY", "iShares MSCI South Korea fund"],
  ["F", "Ford Motor"],
  ["FICO", "Fair Isaac Corporation"],
  ["FIG", "Figma Inc."],
  ["FISV", "Fiserv Inc."],
  ["FIX", "Comfort Systems USA Inc."],
  ["FLNC", "Fluence Energy"],
  ["FLY", "Firefly Aerospace Inc."],
  ["FTNT", "Fortinet Inc."],
  ["FUTU", "Futu Holdings"],
  ["GE", "GE Aerospace"],
  ["GEV", "GE Vernova Inc."],
  ["GLD", "SPDR Gold Shares"],
  ["GLW", "Corning"],
  ["GLXY", "Galaxy Digital Inc."],
  ["GME", "GameStop"],
  ["GOOGL", "Alphabet Class A"],
  ["HII", "Huntington Ingalls Industries Inc."],
  ["HIMS", "Hims & Hers Health Inc."],
  ["HPE", "Hewlett Packard Enterprise Company"],
  ["HWM", "Howmet Aerospace Inc."],
  ["IBM", "International Business Machines"],
  ["IBRX", "ImmunityBio Inc."],
  ["INDA", "iShares MSCI India ETF"],
  ["INFQ", "Infleqtion Inc."],
  ["INOD", "Innodata"],
  ["INTC", "Intel"],
  ["INTU", "Intuit"],
  ["IONQ", "IonQ"],
  ["IREN", "IREN Limited"],
  ["JBL", "Jabil Inc."],
  ["JNJ", "Johnson & Johnson"],
  ["JOBY", "Joby Aviation Inc."],
  ["KLAC", "KLA Corporation"],
  ["KSS", "Kohl's Corporation"],
  ["KTOS", "Kratos Defense & Security Solutions Inc."],
  ["LHX", "L3Harris Technologies Inc."],
  ["LITE", "Lumentum"],
  ["LLY", "Eli Lilly"],
  ["LMT", "Lockheed Martin Corp."],
  ["LRCX", "Lam Research Corporation"],
  ["LULU", "Lululemon"],
  ["LUNR", "Intuitive Machines"],
  ["MDB", "MongoDB"],
  ["META", "Meta Platforms"],
  ["MOD", "Modine Manufacturing Co"],
  ["MPWR", "Monolithic Power Systems Inc."],
  ["MRNA", "Moderna Inc."],
  ["MRVL", "Marvell Technology"],
  ["MSFT", "Microsoft"],
  ["MSTR", "Strategy Inc."],
  ["MTSI", "MACOM Technology Solutions Holdings Inc."],
  ["MU", "Micron Technology"],
  ["MXL", "MaxLinear"],
  ["NASA", "Tema Space Innovators ETF"],
  ["NAVN", "Navan Inc."],
  ["NBIS", "Nebius Group"],
  ["NET", "Cloudflare Inc."],
  ["NFLX", "Netflix"],
  ["NNE", "Nano Nuclear Energy"],
  ["NOK", "Nokia"],
  ["NOW", "ServiceNow"],
  ["NU", "Nu"],
  ["NVDA", "NVIDIA"],
  ["NVTS", "Navitas Semiconductor"],
  ["OKLO", "Oklo Inc."],
  ["ON", "ON Semiconductor Corporation"],
  ["ONTO", "Onto Innovation Inc."],
  ["ORCL", "Oracle"],
  ["OUST", "Ouster Inc."],
  ["P", "Everpure"],
  ["PANW", "Palo Alto Networks Inc."],
  ["PATH", "UiPath Inc."],
  ["PENG", "Penguin Solutions"],
  ["PFE", "Pfizer Inc."],
  ["PL", "Planet Labs PBC"],
  ["PLTR", "Palantir Technologies"],
  ["POET", "POET Technologies"],
  ["POWL", "Powell Industries Inc."],
  ["PR", "Permian Resources"],
  ["PWR", "Quanta Services Inc."],
  ["QBTS", "D-Wave Quantum"],
  ["QCOM", "Qualcomm"],
  ["QNT", "Quantinuum Inc."],
  ["QQQ", "Invesco QQQ"],
  ["QUBT", "Quantum Computing"],
  ["RBLX", "Roblox"],
  ["RCAT", "Red Cat Holdings Inc."],
  ["RDDT", "Reddit"],
  ["RDW", "Redwire"],
  ["RGTI", "Rigetti Computing"],
  ["RIVN", "Rivian Automotive"],
  ["RKLB", "Rocket Lab Corporation"],
  ["RUN", "Sunrun Inc."],
  ["RVI", "RVI"],
  ["SATS", "EchoStar"],
  ["SCHD", "Schwab US Dividend Equity ETF"],
  ["SGOV", "iShares 0-3 Month Treasury Bond ETF"],
  ["SHOP", "Shopify"],
  ["SHY", "iShares 1-3 Year Treasury Bond ETF"],
  ["SIMO", "Silicon Motion Technology Corporation"],
  ["SLS", "SELLAS Life Sciences Group Inc."],
  ["SLV", "iShares Silver Trust"],
  ["SMCI", "Super Micro Computer"],
  ["SMH", "VanEck Semiconductor ETF"],
  ["SMR", "NuScale Power Corporation"],
  ["SNAP", "Snap Inc."],
  ["SNDK", "Sandisk Corporation"],
  ["SNOW", "Snowflake Inc."],
  ["SOFI", "SoFi Technologies"],
  ["SOUN", "SoundHound AI Inc"],
  ["SOXX", "iShares Semiconductor ETF"],
  ["SPCX", "Space Exploration Technologies Corp"],
  ["SPMO", "Invesco S&P 500 Momentum ETF"],
  ["SPY", "SPDR S&P 500 ETF Trust"],
  ["TE", "T1 Energy Inc."],
  ["TEAM", "Atlassian Corporation"],
  ["TEM", "Tempus AI Inc."],
  ["TER", "Teradyne Inc."],
  ["TSEM", "Tower Semiconductor"],
  ["TSLA", "Tesla"],
  ["TSM", "Taiwan Semiconductor Manufacturing"],
  ["TTD", "The Trade Desk Inc."],
  ["TTWO", "Take-Two Interactive Software"],
  ["UMC", "United Microelectronics"],
  ["UNH", "UnitedHealth Group Incorporated"],
  ["UPS", "UPS"],
  ["USAR", "USA Rare Earth"],
  ["USO", "United States Oil Fund"],
  ["VICR", "Vicor Corporation"],
  ["VRT", "Vertiv Holdings Co"],
  ["VSAT", "ViaSat Inc."],
  ["VST", "Vistra Corp."],
  ["VTI", "Vanguard Total Stock Market ETF"],
  ["WDAY", "Workday"],
  ["WDC", "Western Digital Corporation"],
  ["WULF", "TeraWulf Inc."],
  ["WYFI", "WhiteFiber Inc."],
  ["XLK", "Technology Select Sector SPDR ETF"],
  ["XNDU", "Xanadu Quantum"],
  ["XOM", "Exxon Mobil"],
  ["ZETA", "Zeta Global Holdings Corp."],
  ["ZM", "Zoom"],
  ["ZS", "Zscaler"],
]

/** Ticker → company name. */
export const ROBINHOOD_TICKER_NAMES: Readonly<Record<string, string>> = Object.fromEntries(ROBINHOOD_TICKERS)

/** The ticker set, for membership checks. */
export const ROBINHOOD_TICKER_SET: ReadonlySet<string> = new Set(ROBINHOOD_TICKERS.map(([s]) => s))
